Add Quote
narze/awesome-cheab-quotes pull request #56
Opened 2022-10-10 14:38 UTC by eXitHere

2022-10-10 16:58 UTC, Leomotors requested changes

2022-10-11 03:02 UTC, eXitHere commented on README.md
> +-   If you get tired, learn to rest not to quit. [academic]
Fixed kub.

2022-10-11 05:01 UTC, Leomotors approved these changes
😭😭😭

2022-10-11 05:01 UTC, merged

2022-10-11 05:01 UTC, eXitHere commented
> 😭😭😭

Thank ;-;